config/routes.rb
Rails.application.routes.draw do
  resources :url_shorteners
  root to: 'url_shorteners#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url_shortener.rb
class UrlShortener < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/url_shorteners_controller.rb
class UrlShortenersController < ApplicationController
  before_action :set_url_shortener, only: %i[ show edit update destroy ]

  # GET /url_shorteners or /url_shorteners.json
  def index
    @url_shorteners = UrlShortener.all
  end

  # GET /url_shorteners/1 or /url_shorteners/1.json
  def show
  end

  # GET /url_shorteners/new
  def new
    @url_shortener = UrlShortener.new
  end

  # GET /url_shorteners/1/edit
  def edit
  end

  # POST /url_shorteners or /url_shorteners.json
  def create
    @url_shortener = UrlShortener.new(url_shortener_params)

    respond_to do |format|
      if @url_shortener.save
        format.html { redirect_to url_shortener_url(@url_shortener), notice: "Url shortener was successfully created." }
        format.json { render :show, status: :created, location: @url_shortener }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url_shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /url_shorteners/1 or /url_shorteners/1.json
  def update
    respond_to do |format|
      if @url_shortener.update(url_shortener_params)
        format.html { redirect_to url_shortener_url(@url_shortener), notice: "Url shortener was successfully updated." }
        format.json { render :show, status: :ok, location: @url_shortener }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url_shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /url_shorteners/1 or /url_shorteners/1.json
  def destroy
    @url_shortener.destroy

    respond_to do |format|
      format.html { redirect_to url_shorteners_url, notice: "Url shortener was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url_shortener
      @url_shortener = UrlShortener.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_shortener_params
      params.require(:url_shortener).permit(:url_given, :url_shortened)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_shorteners_helper.rb
module UrlShortenersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenges</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url_shorteners/default/_form.html.erb
<%= form_with(model: url_shortener) do |form| %>
  <% if url_shortener.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url_shortener.errors.count, "error") %> prohibited this url_shortener from being saved:</h2>

      <ul>
        <% url_shortener.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url_given %>
    <%= form.text_area :url_given %>
  </div>

  <div class="field">
    <%= form.label :url_shortened %>
    <%= form.text_field :url_shortened %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/url_shorteners/default/edit.html.erb
<h1>Editing Url Shortener</h1>

<%= render 'form', url_shortener: @url_shortener %>

<%= link_to 'Show', @url_shortener %> |
<%= link_to 'Back', url_shorteners_path %>

app/views/url_shorteners/default/new.html.erb
<h1>New Url Shortener</h1>

<%= render 'form', url_shortener: @url_shortener %>

<%= link_to 'Back', url_shorteners_path %>

app/views/url_shorteners/default/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url given:</strong>
  <%= @url_shortener.url_given %>
</p>

<p>
  <strong>Url shortened:</strong>
  <%= @url_shortener.url_shortened %>
</p>

<%= link_to 'Edit', edit_url_shortener_path(@url_shortener) %> |
<%= link_to 'Back', url_shorteners_path %>

app/views/url_shorteners/index.html.erb
<angular_project>
  Loading...
</angular_project>